// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikjncckyorcwqfipkutj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlram5jY2t5b3Jjd3FmaXBrdXRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDI4ODMsImV4cCI6MjA3MTE3ODg4M30.r2dB30ztEZDauZyEBfVfS4cBJCKJcwayeAP9bXQclx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});